text:
  change: change test

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: info-service
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
  r2dbc:
    #    #mariadb
#    url: r2dbc:mariadb://localhost:3306/yamlgenerator
#    username: root
#    password: test1357
  #    #h2-file
    url: r2dbc:h2:file:///C:/Users/skaru/Desktop/yaml-generator/test
    username: sa
    password:

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka