server:
  port: 8888

spring:
  application:
    name: config-service
  kafka:
    bootstrap-servers: localhost:9092
    client-id: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:\\\${user.home}\Desktop\yaml-generator\config-repo
#          search-locations: file:\\\${user.home}\Desktop\Rabbitmq-SpringCloudBus\config-repo

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"

